/// <reference types="vitest" />

import { fileURLToPath, URL } from 'node:url'
import legacy from '@vitejs/plugin-legacy'
import react from '@vitejs/plugin-react'
import { defineConfig } from 'vite'
import { VitePWA } from 'vite-plugin-pwa'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react(),
    legacy(),
    VitePWA({
      registerType: 'autoUpdate',
      // public/manifest.json is hand-maintained (linked directly from index.html) rather than
      // generated by this plugin — keeps the PWA manifest and the existing Capacitor/iOS meta
      // tags in one place instead of two competing sources of truth.
      manifest: false,
      // No auto-injected registration script: main.tsx registers the service worker itself via
      // virtual:pwa-register, gated to skip entirely inside the Capacitor native app (see there
      // for why — the Android build must never run a service worker).
      injectRegister: null,
      workbox: {
        globPatterns: ['**/*.{js,css,html,ico,png,svg,woff,woff2}'],
      },
      devOptions: {
        // Never enable the SW under `vite dev` — offline caching has no business interfering
        // with local development, where every reload should reflect the latest source.
        enabled: false,
      },
    }),
  ],
  resolve: {
    alias: {
      '@domain': fileURLToPath(new URL('./src/domain', import.meta.url)),
      '@modules': fileURLToPath(new URL('./src/modules', import.meta.url)),
      '@components': fileURLToPath(new URL('./src/components', import.meta.url)),
      '@navigation': fileURLToPath(new URL('./src/navigation', import.meta.url)),
      '@store': fileURLToPath(new URL('./src/store', import.meta.url)),
      '@theme': fileURLToPath(new URL('./src/theme', import.meta.url)),
    },
  },
  test: {
    globals: true,
    setupFiles: './src/test/setup.ts',
    projects: [
      {
        extends: true,
        test: {
          name: 'domain',
          environment: 'node',
          include: ['src/domain/**/*.{test,spec}.{ts,tsx}'],
        },
      },
      {
        extends: true,
        test: {
          name: 'ui',
          environment: 'jsdom',
          include: ['src/**/*.{test,spec}.{ts,tsx}'],
          exclude: ['src/domain/**'],
        },
      },
    ],
  }
})
